#!/bin/sh
# Check the warranty once a day

# Skip manual check
if [ "$1" = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

# Seconds between checks
CHECK=860000

# Make sure the cache directory exists
DIR=$(dirname $0)
mkdir -p "$DIR/cache"

# Check if geekbench.txt exists
if [ -e "$DIR/cache/geekbench.txt" ]; then

	# Get current time
	TIME=$(date +%s)

	# Get file modified time
	FILEMTIME=$(stat -f "%Sm" -t "%s" "$DIR/cache/geekbench.txt")

	# Calculate the difference in seconds
	DIFF=$(( $TIME - $FILEMTIME ))

	if [ $DIFF -gt $CHECK ]; then
		# Store date in file
		date > "$DIR/cache/geekbench.txt"
	fi

else

	# Store date in file
	date > "$DIR/cache/geekbench.txt"
	
fi

exit 0
